[workspace]
resolver = "2"
members = [
    "blaktail-config",
    "blaktaild",
    "blaktail-coord",
    "blaktail-relay",
    "blaktail-gateway",
    "blaktail-ingress",
    "blaktail-ios-wg",
    "blaktail-agentgw",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/jusso-dev/BlakTail"
